// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(lush_coreFFI)
import lush_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_lush_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_lush_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureLushCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol CoreProtocol: AnyObject, Sendable {
    
    func applyNoteMark(url: String, start: UInt64, end: UInt64, name: String, valueJson: String?, title: String, heads: [String]) throws  -> [String]
    
    func assetBytes(url: String) throws  -> Data
    
    func assetInfo(url: String)  -> AssetInfo?
    
    func assetVision(url: String)  -> AssetVision?
    
    /**
     * Store binary data as a patchwork UnixFileEntry doc; returns its URL.
     */
    func createAsset(name: String, `extension`: String, mimeType: String, data: Data) throws  -> String
    
    func createNote(title: String) throws  -> String
    
    /**
     * Create a note doc immediately without waiting for the folder to be in
     * memory. The caller is responsible for linking it to a folder separately.
     */
    func createNoteDoc(title: String) throws  -> String
    
    /**
     * Create a note inside a specific folder doc.
     */
    func createNoteIn(folderUrl: String, title: String) throws  -> String
    
    func createScriptIn(folderUrl: String, name: String) throws  -> String
    
    /**
     * Create a folder doc inside the current folder.
     */
    func createSubfolder(title: String) throws  -> String
    
    /**
     * Create a folder doc inside a specific folder doc.
     */
    func createSubfolderIn(folderUrl: String, title: String) throws  -> String
    
    func deleteNote(url: String) throws 
    
    func docChangeCount(url: String)  -> UInt32
    
    /**
     * Current automerge heads for any doc we hold locally. Returns an empty
     * vec if the doc isn't tracked or has no changes.
     */
    func docHeads(url: String)  -> [String]
    
    /**
     * Open an existing folder doc (waiting for it to arrive if needed) or
     * create a fresh one. Returns the folder's automerge URL.
     */
    func ensureFolder(existingUrl: String?) throws  -> String
    
    /**
     * Entries of any folder doc we hold locally (no waiting, no network).
     */
    func folderEntriesOf(url: String)  -> [NoteInfo]
    
    func folderTitle()  -> String
    
    func folderUrl()  -> String?
    
    func isConnected()  -> Bool
    
    /**
     * Link a note into the current folder. The folder doc is loaded from
     * local storage on demand if not already in memory.
     */
    func linkNoteToFolder(noteUrl: String, title: String) throws 
    
    func listNotes()  -> [NoteInfo]
    
    /**
     * Move an entry from one folder doc to another, refusing cycles.
     */
    func moveEntry(fromFolder: String, toFolder: String, url: String) throws 
    
    /**
     * Unix seconds of the newest change in the doc (0 when unknown).
     */
    func noteModified(url: String)  -> Int64
    
    func notePreview(url: String)  -> String
    
    func noteSpansJson(url: String) throws  -> String
    
    func noteSpansSnapshot(url: String) throws  -> NoteSpansSnapshot
    
    /**
     * Bytes of the first embedded image in a note, if the asset is already
     * held locally. Returns None without any network I/O.
     */
    func noteThumbnailBytes(url: String)  -> Data?
    
    func noteTitle(url: String)  -> String
    
    /**
     * Start tracking + syncing a note. Returns once the doc is available
     * locally (immediately for docs we already have).
     */
    func openNote(url: String) throws 
    
    /**
     * Start tracking + syncing docs without waiting for them to arrive,
     * recursing into subfolders. Once a doc lands, its legacy scalar
     * strings are normalized to Text.
     */
    func prefetchNotes(urls: [String]) 
    
    /**
     * Remove an entry from a specific folder doc.
     */
    func removeEntry(folderUrl: String, url: String) throws 
    
    /**
     * Rename a doc and its entry inside a specific folder doc.
     */
    func renameEntry(folderUrl: String, url: String, title: String) throws 
    
    func renameNote(url: String, title: String) throws 
    
    func resyncDoc(url: String) throws 
    
    /**
     * Full-text search across every locally indexed note. The index is local
     * to this device and is updated as prefetched docs land or change.
     */
    func searchNotes(query: String)  -> [SearchHit]
    
    func setDelegate(delegate: CoreDelegate) 
    
    /**
     * Flush all pending saves and do a best-effort final sync before the app
     * exits. Should be called from applicationWillTerminate / sceneDidDisconnect.
     */
    func shutdown() 
    
    func spliceNoteText(url: String, index: UInt64, deleteCount: Int64, insert: String, title: String, heads: [String]) throws  -> [String]
    
    /**
     * Set the active folder immediately from a known URL, then load the doc
     * from local storage in the background. Returns before any I/O completes,
     * so the UI can be ready immediately.
     */
    func startFolderUrl(url: String) throws 
    
    /**
     * Write Vision OCR + description onto a UnixFileEntry doc.
     */
    func updateAssetVision(url: String, description: String, ocr: String) throws 
    
    func updateNoteSpans(url: String, spansJson: String) throws 
    
    /**
     * Like `update_note_spans`, but the commit is stamped with the given
     * unix-seconds timestamp — used by importers to preserve edit dates.
     */
    func updateNoteSpansAt(url: String, spansJson: String, timestamp: Int64) throws 
    
}
open class Core: CoreProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_lush_core_fn_clone_core(self.pointer, $0) }
    }
public convenience init(dataDir: String, serverUrl: String?)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_constructor_core_new(
        FfiConverterString.lower(dataDir),
        FfiConverterOptionString.lower(serverUrl),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_lush_core_fn_free_core(pointer, $0) }
    }

    

    
open func applyNoteMark(url: String, start: UInt64, end: UInt64, name: String, valueJson: String?, title: String, heads: [String])throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_apply_note_mark(self.uniffiClonePointer(),
        FfiConverterString.lower(url),
        FfiConverterUInt64.lower(start),
        FfiConverterUInt64.lower(end),
        FfiConverterString.lower(name),
        FfiConverterOptionString.lower(valueJson),
        FfiConverterString.lower(title),
        FfiConverterSequenceString.lower(heads),$0
    )
})
}
    
open func assetBytes(url: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_asset_bytes(self.uniffiClonePointer(),
        FfiConverterString.lower(url),$0
    )
})
}
    
open func assetInfo(url: String) -> AssetInfo?  {
    return try!  FfiConverterOptionTypeAssetInfo.lift(try! rustCall() {
    uniffi_lush_core_fn_method_core_asset_info(self.uniffiClonePointer(),
        FfiConverterString.lower(url),$0
    )
})
}
    
open func assetVision(url: String) -> AssetVision?  {
    return try!  FfiConverterOptionTypeAssetVision.lift(try! rustCall() {
    uniffi_lush_core_fn_method_core_asset_vision(self.uniffiClonePointer(),
        FfiConverterString.lower(url),$0
    )
})
}
    
    /**
     * Store binary data as a patchwork UnixFileEntry doc; returns its URL.
     */
open func createAsset(name: String, `extension`: String, mimeType: String, data: Data)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_create_asset(self.uniffiClonePointer(),
        FfiConverterString.lower(name),
        FfiConverterString.lower(`extension`),
        FfiConverterString.lower(mimeType),
        FfiConverterData.lower(data),$0
    )
})
}
    
open func createNote(title: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_create_note(self.uniffiClonePointer(),
        FfiConverterString.lower(title),$0
    )
})
}
    
    /**
     * Create a note doc immediately without waiting for the folder to be in
     * memory. The caller is responsible for linking it to a folder separately.
     */
open func createNoteDoc(title: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_create_note_doc(self.uniffiClonePointer(),
        FfiConverterString.lower(title),$0
    )
})
}
    
    /**
     * Create a note inside a specific folder doc.
     */
open func createNoteIn(folderUrl: String, title: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_create_note_in(self.uniffiClonePointer(),
        FfiConverterString.lower(folderUrl),
        FfiConverterString.lower(title),$0
    )
})
}
    
open func createScriptIn(folderUrl: String, name: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_create_script_in(self.uniffiClonePointer(),
        FfiConverterString.lower(folderUrl),
        FfiConverterString.lower(name),$0
    )
})
}
    
    /**
     * Create a folder doc inside the current folder.
     */
open func createSubfolder(title: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_create_subfolder(self.uniffiClonePointer(),
        FfiConverterString.lower(title),$0
    )
})
}
    
    /**
     * Create a folder doc inside a specific folder doc.
     */
open func createSubfolderIn(folderUrl: String, title: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_create_subfolder_in(self.uniffiClonePointer(),
        FfiConverterString.lower(folderUrl),
        FfiConverterString.lower(title),$0
    )
})
}
    
open func deleteNote(url: String)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_delete_note(self.uniffiClonePointer(),
        FfiConverterString.lower(url),$0
    )
}
}
    
open func docChangeCount(url: String) -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_lush_core_fn_method_core_doc_change_count(self.uniffiClonePointer(),
        FfiConverterString.lower(url),$0
    )
})
}
    
    /**
     * Current automerge heads for any doc we hold locally. Returns an empty
     * vec if the doc isn't tracked or has no changes.
     */
open func docHeads(url: String) -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_lush_core_fn_method_core_doc_heads(self.uniffiClonePointer(),
        FfiConverterString.lower(url),$0
    )
})
}
    
    /**
     * Open an existing folder doc (waiting for it to arrive if needed) or
     * create a fresh one. Returns the folder's automerge URL.
     */
open func ensureFolder(existingUrl: String?)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_ensure_folder(self.uniffiClonePointer(),
        FfiConverterOptionString.lower(existingUrl),$0
    )
})
}
    
    /**
     * Entries of any folder doc we hold locally (no waiting, no network).
     */
open func folderEntriesOf(url: String) -> [NoteInfo]  {
    return try!  FfiConverterSequenceTypeNoteInfo.lift(try! rustCall() {
    uniffi_lush_core_fn_method_core_folder_entries_of(self.uniffiClonePointer(),
        FfiConverterString.lower(url),$0
    )
})
}
    
open func folderTitle() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_lush_core_fn_method_core_folder_title(self.uniffiClonePointer(),$0
    )
})
}
    
open func folderUrl() -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_lush_core_fn_method_core_folder_url(self.uniffiClonePointer(),$0
    )
})
}
    
open func isConnected() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_lush_core_fn_method_core_is_connected(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Link a note into the current folder. The folder doc is loaded from
     * local storage on demand if not already in memory.
     */
open func linkNoteToFolder(noteUrl: String, title: String)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_link_note_to_folder(self.uniffiClonePointer(),
        FfiConverterString.lower(noteUrl),
        FfiConverterString.lower(title),$0
    )
}
}
    
open func listNotes() -> [NoteInfo]  {
    return try!  FfiConverterSequenceTypeNoteInfo.lift(try! rustCall() {
    uniffi_lush_core_fn_method_core_list_notes(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Move an entry from one folder doc to another, refusing cycles.
     */
open func moveEntry(fromFolder: String, toFolder: String, url: String)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_move_entry(self.uniffiClonePointer(),
        FfiConverterString.lower(fromFolder),
        FfiConverterString.lower(toFolder),
        FfiConverterString.lower(url),$0
    )
}
}
    
    /**
     * Unix seconds of the newest change in the doc (0 when unknown).
     */
open func noteModified(url: String) -> Int64  {
    return try!  FfiConverterInt64.lift(try! rustCall() {
    uniffi_lush_core_fn_method_core_note_modified(self.uniffiClonePointer(),
        FfiConverterString.lower(url),$0
    )
})
}
    
open func notePreview(url: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_lush_core_fn_method_core_note_preview(self.uniffiClonePointer(),
        FfiConverterString.lower(url),$0
    )
})
}
    
open func noteSpansJson(url: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_note_spans_json(self.uniffiClonePointer(),
        FfiConverterString.lower(url),$0
    )
})
}
    
open func noteSpansSnapshot(url: String)throws  -> NoteSpansSnapshot  {
    return try  FfiConverterTypeNoteSpansSnapshot_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_note_spans_snapshot(self.uniffiClonePointer(),
        FfiConverterString.lower(url),$0
    )
})
}
    
    /**
     * Bytes of the first embedded image in a note, if the asset is already
     * held locally. Returns None without any network I/O.
     */
open func noteThumbnailBytes(url: String) -> Data?  {
    return try!  FfiConverterOptionData.lift(try! rustCall() {
    uniffi_lush_core_fn_method_core_note_thumbnail_bytes(self.uniffiClonePointer(),
        FfiConverterString.lower(url),$0
    )
})
}
    
open func noteTitle(url: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_lush_core_fn_method_core_note_title(self.uniffiClonePointer(),
        FfiConverterString.lower(url),$0
    )
})
}
    
    /**
     * Start tracking + syncing a note. Returns once the doc is available
     * locally (immediately for docs we already have).
     */
open func openNote(url: String)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_open_note(self.uniffiClonePointer(),
        FfiConverterString.lower(url),$0
    )
}
}
    
    /**
     * Start tracking + syncing docs without waiting for them to arrive,
     * recursing into subfolders. Once a doc lands, its legacy scalar
     * strings are normalized to Text.
     */
open func prefetchNotes(urls: [String])  {try! rustCall() {
    uniffi_lush_core_fn_method_core_prefetch_notes(self.uniffiClonePointer(),
        FfiConverterSequenceString.lower(urls),$0
    )
}
}
    
    /**
     * Remove an entry from a specific folder doc.
     */
open func removeEntry(folderUrl: String, url: String)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_remove_entry(self.uniffiClonePointer(),
        FfiConverterString.lower(folderUrl),
        FfiConverterString.lower(url),$0
    )
}
}
    
    /**
     * Rename a doc and its entry inside a specific folder doc.
     */
open func renameEntry(folderUrl: String, url: String, title: String)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_rename_entry(self.uniffiClonePointer(),
        FfiConverterString.lower(folderUrl),
        FfiConverterString.lower(url),
        FfiConverterString.lower(title),$0
    )
}
}
    
open func renameNote(url: String, title: String)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_rename_note(self.uniffiClonePointer(),
        FfiConverterString.lower(url),
        FfiConverterString.lower(title),$0
    )
}
}
    
open func resyncDoc(url: String)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_resync_doc(self.uniffiClonePointer(),
        FfiConverterString.lower(url),$0
    )
}
}
    
    /**
     * Full-text search across every locally indexed note. The index is local
     * to this device and is updated as prefetched docs land or change.
     */
open func searchNotes(query: String) -> [SearchHit]  {
    return try!  FfiConverterSequenceTypeSearchHit.lift(try! rustCall() {
    uniffi_lush_core_fn_method_core_search_notes(self.uniffiClonePointer(),
        FfiConverterString.lower(query),$0
    )
})
}
    
open func setDelegate(delegate: CoreDelegate)  {try! rustCall() {
    uniffi_lush_core_fn_method_core_set_delegate(self.uniffiClonePointer(),
        FfiConverterCallbackInterfaceCoreDelegate_lower(delegate),$0
    )
}
}
    
    /**
     * Flush all pending saves and do a best-effort final sync before the app
     * exits. Should be called from applicationWillTerminate / sceneDidDisconnect.
     */
open func shutdown()  {try! rustCall() {
    uniffi_lush_core_fn_method_core_shutdown(self.uniffiClonePointer(),$0
    )
}
}
    
open func spliceNoteText(url: String, index: UInt64, deleteCount: Int64, insert: String, title: String, heads: [String])throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_splice_note_text(self.uniffiClonePointer(),
        FfiConverterString.lower(url),
        FfiConverterUInt64.lower(index),
        FfiConverterInt64.lower(deleteCount),
        FfiConverterString.lower(insert),
        FfiConverterString.lower(title),
        FfiConverterSequenceString.lower(heads),$0
    )
})
}
    
    /**
     * Set the active folder immediately from a known URL, then load the doc
     * from local storage in the background. Returns before any I/O completes,
     * so the UI can be ready immediately.
     */
open func startFolderUrl(url: String)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_start_folder_url(self.uniffiClonePointer(),
        FfiConverterString.lower(url),$0
    )
}
}
    
    /**
     * Write Vision OCR + description onto a UnixFileEntry doc.
     */
open func updateAssetVision(url: String, description: String, ocr: String)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_update_asset_vision(self.uniffiClonePointer(),
        FfiConverterString.lower(url),
        FfiConverterString.lower(description),
        FfiConverterString.lower(ocr),$0
    )
}
}
    
open func updateNoteSpans(url: String, spansJson: String)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_update_note_spans(self.uniffiClonePointer(),
        FfiConverterString.lower(url),
        FfiConverterString.lower(spansJson),$0
    )
}
}
    
    /**
     * Like `update_note_spans`, but the commit is stamped with the given
     * unix-seconds timestamp — used by importers to preserve edit dates.
     */
open func updateNoteSpansAt(url: String, spansJson: String, timestamp: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_lush_core_fn_method_core_update_note_spans_at(self.uniffiClonePointer(),
        FfiConverterString.lower(url),
        FfiConverterString.lower(spansJson),
        FfiConverterInt64.lower(timestamp),$0
    )
}
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Core

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Core {
        return Core(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Core) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Core {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Core, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCore_lift(_ pointer: UnsafeMutableRawPointer) throws -> Core {
    return try FfiConverterTypeCore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCore_lower(_ value: Core) -> UnsafeMutableRawPointer {
    return FfiConverterTypeCore.lower(value)
}




public struct AssetInfo {
    public var name: String
    public var mimeType: String
    public var `extension`: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, mimeType: String, `extension`: String) {
        self.name = name
        self.mimeType = mimeType
        self.`extension` = `extension`
    }
}

#if compiler(>=6)
extension AssetInfo: Sendable {}
#endif


extension AssetInfo: Equatable, Hashable {
    public static func ==(lhs: AssetInfo, rhs: AssetInfo) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.mimeType != rhs.mimeType {
            return false
        }
        if lhs.`extension` != rhs.`extension` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(mimeType)
        hasher.combine(`extension`)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAssetInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AssetInfo {
        return
            try AssetInfo(
                name: FfiConverterString.read(from: &buf), 
                mimeType: FfiConverterString.read(from: &buf), 
                extension: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AssetInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.mimeType, into: &buf)
        FfiConverterString.write(value.`extension`, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAssetInfo_lift(_ buf: RustBuffer) throws -> AssetInfo {
    return try FfiConverterTypeAssetInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAssetInfo_lower(_ value: AssetInfo) -> RustBuffer {
    return FfiConverterTypeAssetInfo.lower(value)
}


public struct AssetVision {
    public var description: String
    public var ocr: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(description: String, ocr: String) {
        self.description = description
        self.ocr = ocr
    }
}

#if compiler(>=6)
extension AssetVision: Sendable {}
#endif


extension AssetVision: Equatable, Hashable {
    public static func ==(lhs: AssetVision, rhs: AssetVision) -> Bool {
        if lhs.description != rhs.description {
            return false
        }
        if lhs.ocr != rhs.ocr {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(description)
        hasher.combine(ocr)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAssetVision: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AssetVision {
        return
            try AssetVision(
                description: FfiConverterString.read(from: &buf), 
                ocr: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AssetVision, into buf: inout [UInt8]) {
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterString.write(value.ocr, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAssetVision_lift(_ buf: RustBuffer) throws -> AssetVision {
    return try FfiConverterTypeAssetVision.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAssetVision_lower(_ value: AssetVision) -> RustBuffer {
    return FfiConverterTypeAssetVision.lower(value)
}


public struct NoteInfo {
    public var url: String
    public var name: String
    public var kind: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(url: String, name: String, kind: String) {
        self.url = url
        self.name = name
        self.kind = kind
    }
}

#if compiler(>=6)
extension NoteInfo: Sendable {}
#endif


extension NoteInfo: Equatable, Hashable {
    public static func ==(lhs: NoteInfo, rhs: NoteInfo) -> Bool {
        if lhs.url != rhs.url {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(url)
        hasher.combine(name)
        hasher.combine(kind)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNoteInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NoteInfo {
        return
            try NoteInfo(
                url: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: NoteInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNoteInfo_lift(_ buf: RustBuffer) throws -> NoteInfo {
    return try FfiConverterTypeNoteInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNoteInfo_lower(_ value: NoteInfo) -> RustBuffer {
    return FfiConverterTypeNoteInfo.lower(value)
}


public struct NoteSpansSnapshot {
    public var spansJson: String
    public var heads: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(spansJson: String, heads: [String]) {
        self.spansJson = spansJson
        self.heads = heads
    }
}

#if compiler(>=6)
extension NoteSpansSnapshot: Sendable {}
#endif


extension NoteSpansSnapshot: Equatable, Hashable {
    public static func ==(lhs: NoteSpansSnapshot, rhs: NoteSpansSnapshot) -> Bool {
        if lhs.spansJson != rhs.spansJson {
            return false
        }
        if lhs.heads != rhs.heads {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(spansJson)
        hasher.combine(heads)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNoteSpansSnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NoteSpansSnapshot {
        return
            try NoteSpansSnapshot(
                spansJson: FfiConverterString.read(from: &buf), 
                heads: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: NoteSpansSnapshot, into buf: inout [UInt8]) {
        FfiConverterString.write(value.spansJson, into: &buf)
        FfiConverterSequenceString.write(value.heads, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNoteSpansSnapshot_lift(_ buf: RustBuffer) throws -> NoteSpansSnapshot {
    return try FfiConverterTypeNoteSpansSnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNoteSpansSnapshot_lower(_ value: NoteSpansSnapshot) -> RustBuffer {
    return FfiConverterTypeNoteSpansSnapshot.lower(value)
}


public struct SearchHit {
    public var url: String
    public var name: String
    public var snippet: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(url: String, name: String, snippet: String) {
        self.url = url
        self.name = name
        self.snippet = snippet
    }
}

#if compiler(>=6)
extension SearchHit: Sendable {}
#endif


extension SearchHit: Equatable, Hashable {
    public static func ==(lhs: SearchHit, rhs: SearchHit) -> Bool {
        if lhs.url != rhs.url {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.snippet != rhs.snippet {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(url)
        hasher.combine(name)
        hasher.combine(snippet)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchHit: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchHit {
        return
            try SearchHit(
                url: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                snippet: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SearchHit, into buf: inout [UInt8]) {
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.snippet, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchHit_lift(_ buf: RustBuffer) throws -> SearchHit {
    return try FfiConverterTypeSearchHit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchHit_lower(_ value: SearchHit) -> RustBuffer {
    return FfiConverterTypeSearchHit.lower(value)
}


public enum CoreError: Swift.Error {

    
    
    case General(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreError: FfiConverterRustBuffer {
    typealias SwiftType = CoreError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .General(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CoreError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .General(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lift(_ buf: RustBuffer) throws -> CoreError {
    return try FfiConverterTypeCoreError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lower(_ value: CoreError) -> RustBuffer {
    return FfiConverterTypeCoreError.lower(value)
}


extension CoreError: Equatable, Hashable {}




extension CoreError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}







public protocol CoreDelegate: AnyObject, Sendable {
    
    func onDocChanged(url: String) 
    
    func onConnectionChanged(connected: Bool) 
    
    func onSyncEvent(message: String) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceCoreDelegate {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceCoreDelegate] = [UniffiVTableCallbackInterfaceCoreDelegate(
        onDocChanged: { (
            uniffiHandle: UInt64,
            url: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceCoreDelegate.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onDocChanged(
                     url: try FfiConverterString.lift(url)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onConnectionChanged: { (
            uniffiHandle: UInt64,
            connected: Int8,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceCoreDelegate.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onConnectionChanged(
                     connected: try FfiConverterBool.lift(connected)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onSyncEvent: { (
            uniffiHandle: UInt64,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceCoreDelegate.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onSyncEvent(
                     message: try FfiConverterString.lift(message)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceCoreDelegate.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface CoreDelegate: handle missing in uniffiFree")
            }
        }
    )]
}

private func uniffiCallbackInitCoreDelegate() {
    uniffi_lush_core_fn_init_callback_vtable_coredelegate(UniffiCallbackInterfaceCoreDelegate.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceCoreDelegate {
    fileprivate static let handleMap = UniffiHandleMap<CoreDelegate>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceCoreDelegate : FfiConverter {
    typealias SwiftType = CoreDelegate
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceCoreDelegate_lift(_ handle: UInt64) throws -> CoreDelegate {
    return try FfiConverterCallbackInterfaceCoreDelegate.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceCoreDelegate_lower(_ v: CoreDelegate) -> UInt64 {
    return FfiConverterCallbackInterfaceCoreDelegate.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeAssetInfo: FfiConverterRustBuffer {
    typealias SwiftType = AssetInfo?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeAssetInfo.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeAssetInfo.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeAssetVision: FfiConverterRustBuffer {
    typealias SwiftType = AssetVision?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeAssetVision.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeAssetVision.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeNoteInfo: FfiConverterRustBuffer {
    typealias SwiftType = [NoteInfo]

    public static func write(_ value: [NoteInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeNoteInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [NoteInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [NoteInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeNoteInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSearchHit: FfiConverterRustBuffer {
    typealias SwiftType = [SearchHit]

    public static func write(_ value: [SearchHit], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSearchHit.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SearchHit] {
        let len: Int32 = try readInt(&buf)
        var seq = [SearchHit]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSearchHit.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_lush_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_lush_core_checksum_method_core_apply_note_mark() != 29508) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_asset_bytes() != 18011) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_asset_info() != 61101) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_asset_vision() != 43383) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_create_asset() != 18937) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_create_note() != 43728) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_create_note_doc() != 48812) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_create_note_in() != 47187) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_create_script_in() != 25586) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_create_subfolder() != 47650) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_create_subfolder_in() != 43470) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_delete_note() != 536) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_doc_change_count() != 49864) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_doc_heads() != 4598) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_ensure_folder() != 6376) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_folder_entries_of() != 63955) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_folder_title() != 65443) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_folder_url() != 41616) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_is_connected() != 16465) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_link_note_to_folder() != 10426) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_list_notes() != 43939) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_move_entry() != 40698) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_note_modified() != 42759) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_note_preview() != 9633) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_note_spans_json() != 37448) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_note_spans_snapshot() != 8051) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_note_thumbnail_bytes() != 37100) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_note_title() != 56454) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_open_note() != 42116) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_prefetch_notes() != 23856) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_remove_entry() != 62609) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_rename_entry() != 44827) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_rename_note() != 13351) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_resync_doc() != 27414) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_search_notes() != 27844) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_set_delegate() != 58682) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_shutdown() != 44681) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_splice_note_text() != 25441) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_start_folder_url() != 43861) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_update_asset_vision() != 689) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_update_note_spans() != 5252) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_core_update_note_spans_at() != 42222) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_constructor_core_new() != 29324) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_coredelegate_on_doc_changed() != 53266) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_coredelegate_on_connection_changed() != 65433) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lush_core_checksum_method_coredelegate_on_sync_event() != 24982) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitCoreDelegate()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureLushCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all